import assert from 'node:assert/strict';
import {calculate,initialPrices} from './dist/model.mjs';
const s={length:10,width:10,floors:1,height1:3,height2:2.8,foundation:'slab',wall:'gas',roofShape:'gable',roofWarm:'warm',cover:'metal',glazing:'15',doors:1,doorArea:2.1,facade:'none',soffit:'none',gutter:'none',interior:'none',lintels:'included',partitionArea:0,deliveryIncluded:true};
const calc=(change={},rates={})=>calculate({...s,...change},{...initialPrices,...rates});
assert.equal(calc().total,5149560);
assert.equal(calc({cover:'soft'}).total-calc().total,280000);
assert.equal(calc({foundation:'usp'}).total-calc().total,245100);
assert.equal(calc({interior:'whitebox',heating:true,electric:true,plasterArea:200,plumbing:10}).total-calc().total,2600000);
assert.equal(calc({interior:'separate',heating:true,electric:true}).total-calc().total,1880000);
const shipping={deliveryIncluded:false,deliveryBase:5000,deliveryKm:100,trips:2,legs:2};
assert.equal(calc({...shipping,distance:70}).total-calc({...shipping,distance:35}).total,14000);
assert.equal(calc({floors:1,floorArea:100},{floor:5000}).rows.some(x=>x.label==='Межэтажное перекрытие'),false);
assert.equal(calc({floors:2},{floor:5000}).rows.find(x=>x.label==='Межэтажное перекрытие').amount,500000);
assert.equal(calc({floors:2},{floor:5000}).area,200);
assert.equal(calc({mortgage:500000}).mortgage,5649560);
assert.equal(calc().mortgage,null);
assert.ok(calc({partitionArea:''}).missing.some(x=>x.includes('перегородки')));
assert.ok(calc({roofWarm:'cold'}).missing.some(x=>x.includes('кровля')));
assert.equal(calc({roofWarm:'cold'},{coldRoof:10000}).rows.filter(x=>x.group==='Кровля').length,1);
assert.equal(calc({roofShape:'flat'},{flatRoof:10000}).rows.filter(x=>x.group==='Кровля').length,1);
assert.ok(calc({length:0}).missing.length);
assert.ok(calc({glazing:'manual',glazingArea:200}).missing.some(x=>x.includes('Проёмы')));
assert.ok(calc({deliveryIncluded:false}).missing.length);
assert.equal(calc({glazing:'12.5'}).glazing,12.5);
assert.equal(calc({glazing:'15'}).glazing,15);
assert.equal(calc({facade:'plasterFacade'}).total-calc().total,144.9*9100);
assert.equal(calc().missing.length,0);
assert.equal(calc({foundation:'strip'},{strip:800000}).rows.find(x=>x.group==='Фундамент').amount,800000);
assert.ok(calc({roofOverride:0}).missing.length);
assert.ok(calc({floors:2,floorArea:0}).missing.length);
console.log('PASS: 25 checks — arithmetic, roof, floor, White Box, delivery, missing data, mortgage and openings.');
